# Dependency Review Action configuration
# https://github.com/actions/dependency-review-action

fail-on-severity: moderate

comment-summary-in-pr: always
warn-only: false

# Additional settings
vulnerability-check: true
license-check: true