version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    versioning-strategy: "increase-if-necessary"
    commit-message:
      prefix: "chore"
      include: "scope"