name: push-main

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Post status
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.WEBOPS_TG_TOKEN }}
          CHAT_ID: ${{ secrets.WEBOPS_TG_CHAT_ID }}
          TOPIC_ID: ${{ secrets.WEBOPS_TG_PR_MESSAGE_THREAD_ID }}
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          FULL_HASH=$(git rev-parse HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%s)
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${FULL_HASH}"
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)

          MESSAGE=$(printf '*%s deploy*\n[%s](%s) %s\n\n🚀 pushed to main\n' "$REPO_NAME" "$COMMIT_HASH" "$COMMIT_URL" "$COMMIT_MESSAGE")

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d message_thread_id="${TOPIC_ID}" \
            -d text="${MESSAGE}" \
            -d parse_mode="Markdown"

