name: OWASP ZAP Baseline Scan

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

env:
  OWASP_ZAP_TARGET_URL: https://yearn.fi

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ env.OWASP_ZAP_TARGET_URL }}

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
